on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TINYFD: 1
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        architecture: ['x86', 'x64']
    steps:
      - uses: actions/checkout@v2
      - name: set up python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build
        run: |
          pip install cython wheel
          python setup.py bdist_wheel
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pytinyfd-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.architecture }}
          path: dist/*